### ISSUE TITLE
Systemd-networkd fails to find link

### ISSUE THREAD

**Issue by 17twenty** [gumstix/yocto-manifest#61]
I'm configuring my gumstix to act as a DHCP server and have done the following:
    systemctl enable systemd-networkd
    systemctl enable systemd-resolved
    systemctl enable dhcpd.service
```
 $ cat /etc/systemd/network/eth.network
[Match]
Name=eth*

[Network]
DHCP=none
DNS=8.8.8.8

[Address]
Address=192.168.4.1/24
```
Yet, when I reboot, the status of networkd shows:
Mar 05 05:13:15 overo systemd-networkd[1800]: rtnl: received address for a nonexistent link, ignoring

and ip a and ifconfig show:
```
root@overo:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether be:c9:7e:d3:00:77 brd ff:ff:ff:ff:ff:ff
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq qlen 1000
    link/ether 78:a5:04:26:d7:44 brd ff:ff:ff:ff:ff:ff
root@overo:~# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:12160 (11.8 KiB)  TX bytes:12160 (11.8 KiB)

wlan0     Link encap:Ethernet  HWaddr 78:A5:04:26:D7:44
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Am I doing anything wrong or is this a known issue? If I restart systemd-networkd, then I get the expected output of:
```
 systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled)
   Active: active (running) since Thu 2015-03-05 05:26:38 UTC; 1s ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 2455 (systemd-network)
   Status: "Processing requests..."
   CGroup: /system.slice/systemd-networkd.service
           └─2455 /lib/systemd/systemd-networkd

Mar 05 05:26:38 overo systemd-networkd[2455]: lo              : gained carrier
Mar 05 05:26:38 overo systemd-networkd[2455]: eth0            : link configured
```
and my ifconfig becomes:
```
root@overo:~# ifconfig
eth0      Link encap:Ethernet  HWaddr BE:C9:7E:D3:00:77
          inet addr:192.168.4.1  Bcast:192.168.4.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:684 (684.0 B)  TX bytes:303 (303.0 B)
          Interrupt:32

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:163 errors:0 dropped:0 overruns:0 frame:0
          TX packets:163 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:12361 (12.0 KiB)  TX bytes:12361 (12.0 KiB)

wlan0     Link encap:Ethernet  HWaddr 78:A5:04:26:D7:44
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Is this broken behaviour and is there a workaround, if not how should I properly enable networkd for the gumstix?

**Comment by ashcharles** [comment]
Hmm...this sounds like a dependency issue between system-networkd and dhcpd about when the interface comes up and what IP it gets.  FWIW, we originally tried providing dhcp directly via system-networkd [1] but it proved a little inflexible as yet so we opted for dnsmasq instead [2].
[1] https://github.com/gumstix/meta-gumstix-extras/commit/d29ad0be5f5aaa211b33b8a3aedcdf2f270658cb
[2] https://github.com/gumstix/meta-gumstix-extras/commit/82b48f326d8035b64a0f0c1d36a0a3b7875c4465

**Comment by 17twenty** [comment]
So is there a fix or workaround suggested?

**Comment by 17twenty** [comment]
The issue isn't quite dependency based and more to do with the fact that networkd doesn't see the link so doesn't configure it and then the hardware settles down. I was considering adding a rc.local to systemctl restart systemd-networkd as that seems to fix it.

Surely there's something better? Am I missing a config?

**Comment by ashcharles** [comment]
Any reason not to use dnsmasq?  If nothing else, it is little simpler than dhcpd and seems to work okay with systemd-networkd.  It is not clear to me that this is a bug in meta-gumstix-extra rather than a problem with either system-networkd or dhcpd.  Am I misunderstanding the issue?

**Comment by 17twenty** [comment]
The issue is more about the fact that networkd isn't bringing up the link (regardless of dhcpd being enabled or not) due to it not having the link ready at configure time as mentioned above:

```
$ cat /etc/systemd/network/eth.network
[Match]
Name=eth*

[Network]
DHCP=none
DNS=8.8.8.8

[Address]
Address=192.168.4.1/24
...
$ systemctl status systemd-networkd
...
 Mar 05 05:13:15 overo systemd-networkd[1800]: rtnl: received address for a nonexistent link, ignoring
```

So surely even if we switch to dnsmasq it still wouldn't work as expected (i,e, static IP address with or without DHCP serving).

**Comment by ashcharles** [comment]
I tried replicating by taking a recent console image to which I made the suggested changes to the eth.network file (no other changes/enabling). After a reboot I checked the systemctl status systemd-networkd to see "May 21 18:59:41 overo systemd-networkd[1636]: eth0            : link configured".  The system reported the correct address:
root@overo:~# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 00:15:C9:28:F0:59  
          inet addr:192.168.4.1  Bcast:192.168.4.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:64 (64.0 B)
          Interrupt:32 

Anything else I need to be doing to replicate?

**Comment by ashcharles** [comment]
Closing in lieu of additional issue. Re-open as necessary.
