### ISSUE TITLE
Manifest is not up to date

### ISSUE THREAD

**Issue by fred-lamer** [gumstix/yocto-manifest#66]
Hi,
I looked at the default.xml mainifest and it seems that it's not up to date either on branch master or in tag "fido". The commit's SHA for repo "meta-gumstix" and "meta-gumstix-extras" is not the same as the latest commit on branch fido. I'm sure all other repo are behind too.  
Is it possible to update it?
Thanks

**Comment by fred-lamer** [comment]
@ashcharles could you look into this?

**Comment by ashcharles** [comment]
Thanks for the note---I've pushed cefd8f790bd5639588d9297f829cb10dddc1a8a4 to address the issue.

**Comment by fred-lamer** [comment]
thanks!
