### ISSUE TITLE
Full rebuild failing on subversion

### ISSUE THREAD

**Issue by ranchhand6** [gumstix/yocto-manifest#68]
Am in the process of fully rebuilding a development environment and decided to download and recompile fresh before laying in the product overlay.  Followed the procedure outlined, go the following error:

| /home/rdmsdev/Overo-DCI/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/subversion/1.8.11-r0/subversion-1.8.11/subversion/libsvn_ra_serf/blame.c:25:18: fatal error: serf.h: No such file or directory
|  #include <serf.h>
|                   ^
| compilation terminated.
| Makefile:702: recipe for target 'subversion/libsvn_ra_serf/blame.lo' failed
| make: *** [subversion/libsvn_ra_serf/blame.lo] Error 1
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/rdmsdev/Overo-DCI/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/subversion/1.8.11-r0/temp/log.do_compile.27839)
ERROR: Task 6 (/home/rdmsdev/Overo-DCI/yocto/poky/meta/recipes-devtools/subversion/subversion_1.8.11.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 812 tasks of which 807 didn't need to be rerun and 1 failed.
No currently running tasks (812 of 819)

Summary: 1 task failed:
  /home/rdmsdev/Overo-DCI/yocto/poky/meta/recipes-devtools/subversion/subversion_1.8.11.bb, do_compile

Seems like the "serf" package is not providing a header file for "subversion" to subsequently use.  It looks like it it properly.

Looking a little further, it also looks like there are problems in the poky/meta/recipes-devtools/subversion/subversion_1.8.11.bb file.  The file appears to be auto generated and there are errors near the bottom of the file:

| x86_64-linux-libtool: install: warning: `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build
/build/tmp/work/x86_64-linux/subversion-native/1.8.9-r0/build/subversion/libsvn_ra_local/libsvn_ra_local-1.la' has no
t been installed in `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/sysroots/x86
_64-linux/usr/lib'| x86_64-linux-libtool: install: warning: `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-q
a-logrotate/build/build/tmp/work/x86_64-linux/subversion-native/1.8.9-r0/build/subversion/libsvn_repos/libsvn_repos-1
.la' has not been installed in `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/s
ysroots/x86_64-linux/usr/lib'| /usr/bin/ld: cannot find -lsvn_delta-1| collect2: ld returned 1 exit status| x86_64-li
nux-libtool: install: warning: `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/w
ork/x86_64-linux/subversion-native/1.8.9-r0/build/subversion/libsvn_ra_svn/libsvn_ra_svn-1.la' has not been installed
 in `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/sysroots/x86_64-linux/usr/li
b'| x86_64-linux-libtool: install: warning: `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/buil
d/build/tmp/work/x86_64-linux/subversion-native/1.8.9-r0/build/subversion/libsvn_ra_serf/libsvn_ra_serf-1.la' has not
 been installed in `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/sysroots/x86_
64-linux/usr/lib'
#| x86_64-linux-libtool: install: error: relink `libsvn_ra_serf-1.la' with the above command before installing it
#| x86_64-linux-libtool: install: warning: `../../subversion/libsvn_repos/libsvn_repos-1.la' has not been installed i
n `/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/sysroots/x86_64-linux/usr/lib'
#| /home/pokybuild/yocto-autobuilder/yocto-worker/nightly-qa-logrotate/build/build/tmp/work/x86_64-linux/subversion-n
ative/1.8.9-r0/subversion-1.8.9/build-outputs.mk:1090: recipe for target 'install-serf-lib' failed
#| make: *** [install-serf-lib] Error 1
PARALLEL_MAKEINST = ""

Perhaps this is an upstream yocto problem?

Any assistance appreciated.

**Comment by ranchhand6** [comment]
Turned out to be an upstream subversion problem.  Subversion has a known build bug from an overly aggressive regex in an m4 script that will cause the build to fail if there is a dash ("-") in the path.

Obviously.

**Comment by meerfrau** [comment]
Still present with newest subversion 1.14+:
```
libtool: warning: relinking 'libsvn_fs_fs-1.la'
libtool: install: (cd ./src/trunk/subversion/libsvn_fs_fs; /bin/sh "./src/trunk/libtool"  --tag CC --silent --mode=relink gcc -L/usr/lib -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions -Wformat -w -Wno-deprecated-declarations -fcf-protection -march=native -mtune=native -O2 -pipe -fno-plt -fexceptions -Wformat -w -Wno-deprecated-declarations -fcf-protection -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fuse-ld=mold -rpath /usr/lib -version-info 0 -Wl,--no-undefined -o libsvn_fs_fs-1.la cached_data.lo caching.lo dag.lo dump-index.lo fs.lo fs_fs.lo hotcopy.lo id.lo index.lo load-index.lo lock.lo low_level.lo pack.lo recovery.lo rep-cache.lo rev_file.lo revprops.lo stats.lo temp_serializer.lo transaction.lo tree.lo util.lo verify.lo ../../subversion/libsvn_delta/libsvn_delta-1.la ../../subversion/libsvn_subr/libsvn_subr-1.la -laprutil-1 -lapr-1 ../../subversion/libsvn_fs_util/libsvn_fs_util-1.la -inst-prefix-dir ./pkg/subversion)
mold: error: undefined symbol: svn_txdelta_apply2
>>> referenced by tree.c
>>>               .libs/tree.o:(fs_apply_textdelta)
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libsvn_fs_fs-1.la' with the above command before installing it
```
