### ISSUE TITLE
Error in wic create command

### ISSUE THREAD

**Issue by rajarout86** [gumstix/yocto-manifest#76]
While executing 
$ wic create sdimage-gumstix -e gumstix-xfce-image
The following error is encountered
**Checking basic build environment...
Done.

Creating image(s)...

rootfs_dir: /home/srep-compiler/yocto/build/tmp/work/duovero-poky-linux-gnueabi/gumstix-xfce-image/1.0-r0/rootfs
Error: ERROR: mkfs.ext4 returned '1' instead of 0 (which you probably don't want to ignore, use --debug for details) when creating filesystem from rootfs directory: /home/srep-compiler/yocto/build/tmp/work/duovero-poky-linux-gnueabi/gumstix-xfce-image/1.0-r0/rootfs**

Kindly suggest any solution.

**Comment by yangjiel** [comment]
Sorry for the late reply, please see the solution below.

**Comment by yangjiel** [comment]
If that doesn't help, please reopen either issue and I will help you.
