### ISSUE TITLE
uImage not created and wic fails

### ISSUE THREAD

**Issue by uglyoldbob** [gumstix/yocto-manifest#77]
I was following the guide at https://github.com/gumstix/yocto-manifest

I ran into an issue and believe I have traced to find a reason for the failure.

I changed the image type specified for the wic command to something listed in `wic list images`

When running `wic create sdimage-bootpart -e gumstix-xfce-image` I got the following error.
`Error: exec_cmd: install -m 0644 -D blabla/yocto/build/tmp/deploy/images/overo/uImage /var/tmp/wic/build/boot/uImage returned '1' instead of 0`

So I ran `wic create sdimage-bootpart -e gumstix-xfce-image --debug`
This gives a Debug message that it cannot stat the uImage file `No such file or directory`

I ran the command `ls tmp/deploy/images/overo`
I can't paste the output here due to limitations.
There is a zImage file but no uImage file present.

**Comment by yangjiel** [comment]
There is no more uImage needed for building the image. What branch are you using? I tested on Morty and there is no error or debug message presented.

**Comment by uglyoldbob** [comment]
Fido branch used

**Comment by yangjiel** [comment]
When I run the wic command I get the error
```
Traceback (most recent call last):
  File "/media/ubuntu/Backup/fido/poky/scripts/wic", line 45, in <module>
    from image.help import *
ImportError: No module named help
```
That is wired, I need to find out how to solve this problem first. Is your image for Overo?

**Comment by uglyoldbob** [comment]
Yes. If I remember right it is an overo fire with a chestnut43 expansion board.

**Comment by yangjiel** [comment]
Thank you for your information. I post the solution for those two problems.

For image.help ImportError: No module named help, solution is to change the file in `your_directory/poky/scripts/wic`:
```
scripts_path = os.path.abspath(os.path.dirname(os.path.abspath(sys.argv[0])))
lib_path = scripts_path + '/lib'
sys.path = sys.path + [lib_path]
```
into:
```
scripts_path = os.path.abspath(os.path.dirname(__file__))
lib_path = scripts_path + '/lib'
sys.path.insert(0, lib_path)
```

For your problem, modify your local.conf inside the build/conf/, uncomment `#IMAGE_BOOT_FILES_overo ?= "MLO u-boot.img uImage"` and change it to `IMAGE_BOOT_FILES_overo ?= "MLO u-boot.img"`. 

It seems like the same issue with #76. Tell me if this solve your problem or not. Thank you!

**Comment by uglyoldbob** [comment]
Yes, uncommenting the IMAGE_BOOT_FILES line and removing uImage solved the problem for me.
